version: '3.7'
services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - etl_network

  web:
    build: .
    command: python app.py
    volumes:
      - .:/app
    ports:
      - 80:80
    depends_on:
      - db
    networks:
      - etl_network

volumes:
  postgres_data:

networks:
  etl_network:
    driver: bridge
